server:
  port: 9090

spring:
  datasource:
    username: postgres
    password: AAaa1010
    url: jdbc:postgresql://localhost:5432/db_final
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      springframework:
        web: info
        hibernate: error
        com:
          example:
              education: debug

javatar:
  app:
    jwtSecret: Javatar.comSecretKey
    jwtExpirationMs: 86400000